
services:
  postgres:
    image: postgres:16.2-bookworm
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=handbook
      - POSTGRES_USER=root
      - POSTGRES_DB=handbook